### ISSUE TITLE
Language tags

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#10]
Input is going to be wonky with non-Latin characters until the PCC and/or Sinopia comes out with guidelines, so this might be the problem, but I'm seeing some incorrect language tags. I went back to Sinopia to check that I had indeed inserted the "Russian" language tag for "Игрушки и зверушки", and I did. But, somehow we ended up with:
 bf:title [ a bf:VariantTitle ;
            bf:mainTitle "Toys and little animals"@en,
                "Игрушки и зверушки"@en ],
        [ a bf:Title ;
            bf:mainTitle "Igrushki i zverushki"@ru ] .
URI: https://trellis.sinopia.io/repository/washington/7bb2a32d-0232-440c-b008-0405e1cdc5d5
https://github.com/uwlib-cams/rml/blob/master/output/2020_09_18/work_1/20578541-d001-4b6a-818c-413ee8d77b4a.ttl

**Comment by mcm104** [comment]
This is a known issue -- we're waiting on a response from the RML Mapper developers [https://github.com/RMLio/rmlmapper-java/issues/65](https://github.com/RMLio/rmlmapper-java/issues/65).

Basically, our mapping is using an RML property -- rml:languageMap -- that isn't finished yet. It isn't in their specs, at first we weren't sure why, but once we started noticing these issues, I'm assuming it's because it wasn't working properly.

There are two ways in RML to add language tags to literals. One is in their specs -- rr:language -- which takes a constant language tag and adds it to the literals of properties you tell it to. For example, for P10079, I can write RML code that says the constant value for bf:noteType is always tagged as English -- `"numeric designation for musical work"@en`. However, this doesn't work for properties like title, because we can't predict ahead of time what the language of each literal will be.

The other way is the buggy property rml:languageMap, which -- in theory -- looks for language tags in the source data. For example:
`<rdaw:P10332 xml:lang="rus">Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Rasskazy</rdaw:P10332>`
I would write RML code that looks for the value of P10332 to take as a literal, and then looks to see if it has attribute xml:lang. It does, so it should append that value to the literal, given us `"Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Rasskazy"@rus`.

However, when a property has multiple values with differing language tags (like here with the two variant titles), it seems to just choose one language tag and apply it to all instances of that property. A really bad example is [here with the record for the Lorax](https://github.com/uwlib-cams/rml/blob/d6f7ec8bd36d776e97c566949d5fc555aa73e5e0/output/2020_09_18/work_1/d0d9f78e-05f1-4594-bdcb-b396ce68f618.ttl#L46). 

So our options are:
1) Tag everything as English using rr:language (bad option)
2) Use rml:languageMap and sometimes get correct language tags and sometimes get incorrect language tags, and hope the RML devs come up with a solution (what we're doing now, but it's not ideal)
3) Skip language tags altogether in instances where we can't reliably predict what the language will be (also not ideal)

**Comment by briesenberg07** [comment]
See also RMLio/rmlmapper-java [issue no. 65](https://github.com/RMLio/rmlmapper-java/issues/65) (*[new response today](https://github.com/RMLio/rmlmapper-java/issues/65#issuecomment-697420300)!*)

**Comment by briesenberg07** [comment]
Should [a literal value like "24 cm"](https://github.com/uwlib-cams/rml/blob/a5086f584eef9ce4b9effb4f7657230a22d43468/output/2020_09_18/instance/5c35ef9b-be8e-4ef4-aa74-61759291e0f4.ttl#L24) have the lang tag stripped?

Or would it be a mistake to add P30169 / has dimensions to the [`no_language_tag_list`](https://github.com/uwlib-cams/rml/blob/a5086f584eef9ce4b9effb4f7657230a22d43468/generateRML/generateRML_v4.py#L321)??

**Comment by gerontakos** [comment]
I would say, until RML can handle it, choice #3, skip language tags when we can't reliably predict. A problem with that: how will we ever know that RML has repaired this problem?

If Melissa can do what Ben recommends about stripping language tags from non-linguistic values, that would be superTeam.

**Comment by mcm104** [comment]
Language tag issue is mostly resolved in new version of generateRML because of the new way of writing "split" blank nodes. However, this means that "no-split" blank nodes (currently only provision activity and title) do not contain mapping for language tags. See [generateRML's README](https://github.com/uwlib-cams/rml/tree/master/generateRML), **"No-split" blank nodes**.
