### ISSUE TITLE
Floating "role"

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#11]
In at least [this instance](https://github.com/uwlib-cams/rml/edit/master/output/2020_09_18/instance/0010d9b0-ec29-4ab0-b25a-9a1a87108dd2.ttl#L47), there are some roles floating around that seem to just be associated with an instance. Where do they come from? An instance can't be a choreographer.

Blarg. It's also [here](https://github.com/uwlib-cams/rml/blob/d6f7ec8bd36d776e97c566949d5fc555aa73e5e0/output/2020_09_18/instance/799422b6-1e5a-4cd2-8587-19ce9e695dad.ttl#L39)

**Comment by CECSpecialistI** [comment]
Pointing straight to lines in code woooooooo!

**Comment by mcm104** [comment]
Oh yikes, good catch! I looked at our mapping and it's a kiegel issue! It's related to an ongoing issue we've had with ";" vs. "; >". Should discuss this at a future meeting, but in the meantime, I've fixed the kiegel with this issue so future output shouldn't have this issue anymore (at least with roles in instances -- other floating properties in other entities could exist because we're not 100% settled on how kiegel should be written)

**Comment by briesenberg07** [comment]
*Following up on Kiegel syntax stuff:*
In the current [sytax explanation draft](https://docs.google.com/document/d/1dWzXwUJIzcQTXgkEV8wnamwXVuWx3r-Yznd1GU8mXxg/edit#heading=h.pnelb3dhfo1y), the rules that @mcm104 's Python script uses to parse Kiegel syntax have been treated as "the truth." I believe that Melissa has been updating our Kiegel mappings to bring them into conformance for some time now, ensuring that [generateRML.py](https://github.com/uwlib-cams/rml/blob/master/generateRML/generateRML_v4.py) functions correctly.

**Comment by gerontakos** [comment]
Nice catch. Glad mcm104 figures these things out. Glad the Kiegel gets updated. I'll review the changes but I'm sure they're ok.

**Comment by gerontakos** [comment]
> Pointing straight to lines in code woooooooo!

if you promise not to tell, I still don't know how to do this...
