### ISSUE TITLE
RDA/RDF data results in TWO values for a BF prop; should (?) be ONE

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#12]
# Floating URI inside provision activity

The formatting for provisionActivity looks pretty good, but it seems like the URI for the agent should be inside the bnode for that Agent:
```
bf:provisionActivity [ a bf:Publication ;
            bf:agent [ a bf:Agent ;
                    rdfs:label "Albert Whitman & Company, Publishers"@en  ],
                <http://id.loc.gov/rwo/agents/n78059801> ; # 'floating URI' here, makes TWO VALUES for bf:agent
            bf:date "1929" ;
            bf:place [ a bf:Place ;
                    rdfs:label "Chicago"@en ] ] ;
```

**Comment by CECSpecialistI** [comment]
Or, if it's just a coincidence that the label and URI for the publisher here are for the same entity, I think we need two separate [a bf:Agent]

**Comment by briesenberg07** [comment]
I don't think we can say whether this is an RML error or an error in our source data with looking at the source as well. To confirm, we are talking about:

* rml/input/2020_09_18/manifestation/[2364b9e2-5c7b-4bb6-81f1-219a045ad614.xml](https://github.com/uwlib-cams/rml/blob/e7d45c8d0743c9213a89632e658a7a662b1229a8/input/2020_09_18/manifestation/2364b9e2-5c7b-4bb6-81f1-219a045ad614.xml)
   * 30176/*has name of publisher* on [L14](https://github.com/uwlib-cams/rml/blob/e7d45c8d0743c9213a89632e658a7a662b1229a8/input/2020_09_18/manifestation/2364b9e2-5c7b-4bb6-81f1-219a045ad614.xml#L14)
   * IRI for Albert Whitman & Company on [L31](https://github.com/uwlib-cams/rml/blob/e7d45c8d0743c9213a89632e658a7a662b1229a8/input/2020_09_18/manifestation/2364b9e2-5c7b-4bb6-81f1-219a045ad614.xml#L31), as value of *has publisher agent*

* rml/output/2020_09_18/instance/[2364b9e2-5c7b-4bb6-81f1-219a045ad614.ttl](https://github.com/uwlib-cams/rml/blob/a39485ffcfa74ecb6b66a30b1e1ecc5f96d777a2/output/2020_09_18/instance/2364b9e2-5c7b-4bb6-81f1-219a045ad614.ttl)
   * See [L23](https://github.com/uwlib-cams/rml/blob/a39485ffcfa74ecb6b66a30b1e1ecc5f96d777a2/output/2020_09_18/instance/2364b9e2-5c7b-4bb6-81f1-219a045ad614.ttl#L23) - L29

If yes...

It's an interesting example. We give an IRI value for *has publisher agent*, but then we provide a literal value for *has name of publisher*. 

The output data is incorrect--converted BF is in effect saying that there are two publisher agents. But given the values in the source data, it sort of makes sense that it is doing so.

(Because our conversion scheme will take the value for *has publisher agent* and output it as a value for **provisionActivity >> Publication > agent\***. It will also take the value for *has name of publisher* and create a bnode value for that same (it appears) **provisionActivity >> Publication > agent**, and then provide the literal value as an rdfs:label on this bnode.)

This might be the kind of thing that is best solved with guidance for catalogers. For example, if you are providing an IRI value for publisher, you need not make any other statements about the publisher on the manifestation.

**Comment by briesenberg07** [comment]
# Another example
* Input [here](https://github.com/uwlib-cams/rml/blob/a5086f584eef9ce4b9effb4f7657230a22d43468/input/2020_09_18/manifestation/5c35ef9b-be8e-4ef4-aa74-61759291e0f4.ttl#L44) and [here](https://github.com/uwlib-cams/rml/blob/a5086f584eef9ce4b9effb4f7657230a22d43468/input/2020_09_18/manifestation/5c35ef9b-be8e-4ef4-aa74-61759291e0f4.ttl#L28), with values for both name of publisher (the literal) and publisher agent (the IRI)
```
[...]
    rdam:P30176 "Little Brown and Company"@eng ;
    rdam:P30083 <http://id.loc.gov/rwo/agents/n80020835> ;
    [...]
```
* Output [here](https://github.com/uwlib-cams/rml/blob/a5086f584eef9ce4b9effb4f7657230a22d43468/output/2020_09_18/instance/5c35ef9b-be8e-4ef4-aa74-61759291e0f4.ttl#L50-L53), resulting in two Agents when there should be one
```
[...]
    bf:provisionActivity [ a bf:Publication ;
        bf:agent [ a bf:Agent ;
            rdfs:label "Little Brown and Company"@en ], 
        <http://id.loc.gov/rwo/agents/n80020835> ; 
[...]
```

**Comment by gerontakos** [comment]
Is it really incorrect? If I said
<http://commentAbove> ex:creator [ a ex:Human ; rdfs:label "Ben R" ], <http://IRI4Ben.edu> .

...what's wrong with that? It's 2 assertions, both correct.

So what's the problem?

CEC says it should be inside the bnode; would that be better as the property of, what, rdf:value? Or is it better as it is, the value of bf:agent?

ries07 says it claims there are two publisher agents -- but is that true? Isn't it the case that there are two assertions about the publisher and that they agree about the identity of the publisher?

I am claiming that this is ok as is. Discuss further?

**Comment by briesenberg07** [comment]
Most interesting @gerontakos !

...thinking...

But if we have the following values for `ex:creator` in your example...
1. An unnamed resource with statements
   * `rdf:type` `ex:Human`
   * `rdfs:label` "Ben R"
2.  http://IRI4Ben.edu

...doesn't this leave us with some ambiguity about whether these are *really* the same resource, or different? Regardless of how well the description of the resource at http://IRI4Ben.edu seems to match with the statements on our unnamed resource?? 

> Isn't it the case that there are two assertions about the publisher and that they agree about the identity of the publisher?

Looking at both this example *and* the original example above, I *don't think* we can say that these statements agree.

**Comment by gerontakos** [comment]
Ambiguity is the problem I see; the statements don't need to agree I suppose, but I believe we want them to be something like "true" or "accurate." I would say both statements are "true" and "accurate." A better solution is almost always possible; how would you like to see this improved? Above you suggest you would like to approach it by changing catalogers' practice. Crystal wants to see the IRI inside the bnode. Is there a BabyRuth-level way to accommodate this data?

**Comment by briesenberg07** [comment]
*Before* moving on to a solution (which we certainly should do) I just want to give one more thought about why the two Agent values seem wonky to me...

*It's because there are two of them!*

I don't think that the cataloger's intent (returning to the original example at the top of this issue, with source RDA/RDF clarified [here](https://github.com/uwlib-cams/rml/issues/12#issuecomment-697111695)) in entering values for both "has publisher agent" and "has name of publisher" was to say that there are two publishers. 

So, then, shouldn't there be only *one* value for `bf:agent` in the output??

**Comment by gerontakos** [comment]
My point on this property is that it's not a big deal and doesn't need to be repaired. It is a bit wonky, and if anyone thinks of a good solution, let's use it. However I think what exists is a pretty good solution. (1) just because you make two assertions using the bf:agent relation doesn't mean there are two agents, it only "means" there are two assertions that use the bf:agent relation. (2) If the data is queried, the "publisher agent" will be much more visible to data consumers if it's the direct value of bf:agent and not buried in a bnode as the value of rdf:value. (3) In the RDA-RDF two assertions exist; although those assertions are distinguished from each other because they use different predicates, this is the way those separate assertions map into BF; it is another case of a many-to-one rdaRelations-to-bibframeRelations situation, demonstrating the inability of BF to accurately accommodate RDA data. Contrary to this, you might ask, how would a cataloger describe this as original BF; I think that's where we would find trouble because this isn't the way it will be done in original BF data. In original BF data we don't need both representations of the same agent -- just to mention one thing. And also Ben is right, original BF wouldn't be so wonky.

**Comment by briesenberg07** [comment]
Thanks for the responses @gerontakos . 

I was questioning whether **"number of values for a given property in RDF data"** should be thought of as representing **"number of 'things' in the real world"**--it's obvious that this is how I approach this particular issue. So it is helpful to hear your perspective. 

I find that I still have a tendency to think in a very strict way about this--"*If there are **two** values for `bf:agent`, it means that there are **two** real-world objects modelled in the data!*" But this may just some idea of mine, not the way RDF data is meant to work?

Probably more importantly, as you point out...

>it is another case of a many-to-one rdaRelations-to-bibframeRelations situation, demonstrating the inability of BF to accurately accommodate RDA data

...so perhaps creating completely sensible BF data isn't possible, or isn't really what our aim should be here. Although again, I'll say that I tend to *want* to do just that--have my cake and eat it too; describe bibliographic entities in sensible RDA/RDF, and sensible BF too...

**Comment by gerontakos** [comment]
This is an interesting problem: should we tirelessly pursue lossless RDA-to-BF? That's been my approach, for two reasons. On the level near theory, I don't want to lose any data; on the practical level, I want to simplify the mapping to help simplify the transformation code.

We could say, let's get lossy -- in the interest of creating BF that looks like bona fide genuine BF. Why not!? Well, because then we'd have to start writing a bunch of conditions in the transformation code: "if there's a rdam:publisherAgent property, use the value of that P; otherwise use the value of rdam:nameOfPublisher and pump it into a bnode." Or, if both Ps exist and we don't want to get lossy, make sure the BF p-v's get combined into the description of a common bnode. You can see the ordeal that creates.

I also advocate for the "wonky" because, I admit it, my derivative BF data is a second class citizen."BFers," I say, "you're lucky we're even providing this." It's arrogant, but deriving bona fide genuine BF from RDA is, among other things, expensive. But if we were really serious about doing this, we'd write the conditions, no? And, therefore, produce Ben's sensible BF. Looking at it from that point of view, Ben and Crystal are serious about this stuff, and Theo is saying, "Lighten up, comrades, this isn't really serious ... yet." But the BF I'm advocating for is a lower quality BF. We could do better.

**Comment by briesenberg07** [comment]
I agree @gerontakos --it is an interesting problem! And I don't think that there is a right or a wrong at this point in the process. I just think that it is a good and an enriching conversation.

And you make some very good points about the tortuous kinds of conditions we'd need (to ask @mcm104 to put) in our code to get 'sensible' BF output from RDA/RDF input...

**Comment by CECSpecialistI** [comment]
I think we've moved on from this issue and since I'm the one who opened it I'm going to close it now. Please reopen if you want to keep talking about it!
