### ISSUE TITLE
Missing agent info

### ISSUE THREAD

**Issue by JianPLee** [uwlib-cams/rml#18]
I'm not sure if this is an issue, but I don't see the agent element in Work2 from the 03/04 output.

https://github.com/uwlib-cams/rml/blob/8c0d538276b49914806a5f08d5344024e9c8a182/output/2021_03_04/work_2_ttl/02c8be46-235a-4bbc-b18d-85065829236d.ttl#L22

**Comment by mcm104** [comment]
I had a look and turns out that this isn't a case of a missing agent, but a role that shouldn't have generated in the first place -- there was a typo in the kiegel syntax! I went in and fixed it, so it shouldn't be a problem going forward. Here's the same expression in the newest output (just under a different filename with the new UUID): [e6bc2183-6a71-4828-8354-8b16c55e3c8b.xml](https://github.com/uwlib-cams/rml/blob/master/output/2021_03_18/work_2_xml/e6bc2183-6a71-4828-8354-8b16c55e3c8b.xml)

Thanks for finding this!
