### ISSUE TITLE
BIBFRAME in Sinopia issue: ISSN RT incorrectly nested as value of bf:identifiedBy

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#40]
bf:identifiedBy value should have been an ISBN but displays incorrectly in the Sinopia RT for <https://api.sinopia.io/resource/3934ee78-8555-4fca-bf15-192a3e92b1bf>. Specifically, it correctly displays as a bf:Identifier with a value but is displayed side-by-side with an incorrect sub-RT WAU:RT:BF2:ISSN. Perhaps a problem for all Instances that use bf:identifiedBy?

**Comment by CECSpecialistI** [comment]
I'm having a tough time understanding this one. Can you show a code snippet of what you're referring to when you say "displayed side-by-side with an incorrect sub-RT WAU:RT:BF2:ISSN"? I can't seem to find that.

**Comment by gerontakos** [comment]
![identifiedBy](https://user-images.githubusercontent.com/6956200/122485807-a117e180-cf8c-11eb-8ddf-afaf4a79acf9.PNG)

**Comment by gerontakos** [comment]
It's not a big deal; something minor in the RT? The same happens for another instance <https://api.sinopia.io/resource/6becebd7-1dbb-41e3-ab71-5030d87b8fbc> that doesn't have an ISSN:
![identifiedBy2](https://user-images.githubusercontent.com/6956200/122486366-c9eca680-cf8d-11eb-9bed-c5c7f0b5bc3d.PNG)

**Comment by CECSpecialistI** [comment]
The ISSN sub-RT is there because it's an option to either add an ISSN or another identifier as a value of identifiedBy. The ISSN value in the first picture is inside the incorrect sub-RT due to cataloger error in the source data. I think this looks fine. Sinopia displays all the possible nested RT's under each property template, that's why they're both there. @gerontakos am I missing the point entirely?

**Comment by CECSpecialistI** [comment]
@gerontakos please re-open if you disagree, but I'm going to close this for the sake of cleaning up issues
